_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  config: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  image: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  path: 0
  path_alias: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  ui_patterns: 0
  ui_patterns_blocks: 0
  ui_patterns_devel: 0
  ui_patterns_field_formatters: 0
  ui_patterns_layouts: 0
  ui_patterns_legacy: 0
  ui_patterns_library: 0
  ui_patterns_views: 0
  ui_styles: 0
  ui_styles_block: 0
  ui_styles_ckeditor5: 0
  ui_styles_layout_builder: 0
  ui_styles_library: 0
  ui_styles_page: 0
  ui_styles_views: 0
  update: 0
  user: 0
  views_ui: 0
  views: 10
  minimal: 1000
theme:
  claro: 0
  gin: 0
  stable9: 0
  ui_suite_uswds: 0
profile: minimal
