_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: fe1100ce-32d0-49de-93dd-0e857d6c6361
name: 'Drupal GovCon 2024 UI Patterns'
mail: something@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/11
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
